### PR TITLE
Initial appveyor config

### LINKED ISSUE #5: set up CI
Given filesystem munging,  Appveyor (or some other windows-based CI) would also be useful.

### PR DESCRIPTION
**Pull request by pjz**
Fix #5 

TODO: Add more python versions to the matrix

### CODE REVIEW

**Comment by whit537** [comment]
Hmm ... why is AppVeyor not showing up in the checks here? Do we not have the hook installed?

**Comment by pjz** [comment]
Looks like it. This one's in your court, I don't have perms.

**Comment by whit537** [comment]
I'm seeing the hook in settings. Let's check AppVeyor ...

**Comment by whit537** [comment]
Looks like the job *is* getting run:

https://ci.appveyor.com/project/gratipay/filesystem-tree-py/build/job/qi9yoc2b2k8894qr

**Comment by whit537** [comment]
We have the webhook configured on GitHub. It is `POST`ing to AppVeyor. AppVeyor is building the project. What we're not getting is the `POST` back to GitHub to update the build status over here: a permissions issue with the @gratipay-gremlin user account we're using for AppVeyor?

**Comment by whit537** [comment]
We *are* getting the `POST`-back over on `aspen-python`.

**Comment by pjz** [comment]
I wonder if it's because it's on a fork? Close this, I'll re-push to a local branch.

**Comment by whit537** [comment]
Hmmm ... I doubt it but could be.

**Pull request closed without merging**
