### PR TITLE
duplicate some content between docs and README

### PR DESCRIPTION
**Pull request by whit537**
What will this look like on GitHub, PyPI, and RtD?

### CODE REVIEW

**Comment by whit537** [comment]
Eh, @pjz?

**Comment by pjz** [comment]
Sure, LGTM.

**Comment by whit537** [comment]
Here goes nothing ...

**Comment by whit537** [comment]
/me waits for http://filesystem-tree-py.readthedocs.org/en/latest/

**Comment by whit537** [comment]
RtD looks good.

**Comment by whit537** [comment]
The `:py:module:` directive isn't available on GitHub, so the README is broken here.

**Comment by pjz** [comment]
meh, there's badges here, which is all I really wanted. The breakage is fairly mild.

**Pull request merged**
