### PR TITLE
Initial appveyor config

### PR DESCRIPTION
**Pull request by pjz**

### CODE REVIEW

**Comment by whit537** [comment]
Hmm ... didn't fix AppVeyor post-back (but still worth having this in a branch instead of a fork).

**Comment by whit537** [comment]
Hypothesis: the @gratipay-gremlin account doesn't have permission to update repo status.

**Comment by whit537** [comment]
> The Status API allows external services to mark commits with a success, failure, error, or pending `state`, which is then reflected in pull requests involving those commits.

https://developer.github.com/v3/repos/statuses/

**Comment by whit537** [comment]
> Users with push access can create commit statuses for a given ref:

:-/

**Comment by pjz** [comment]
sounds reasonable.  So give it perms?

**Comment by whit537** [comment]
To: support@github.com
Subject: finer-grained status permissions

> I'm configuring CI for a few repos using a "[gremlin](https://github.com/gratipay-gremlin)" account, and I had hoped to limit the permissions I gave to this account. However, it appears that @gratipay-gremlin will need push access to repos where we want to use it for CI commit status updates. We can limit the OAuth scope to repo:status, but I had hoped to limit the entire account in order to reduce the value of this account to an attacker.
>
Is there a way to accomplish this? If not, could we get one? Thanks! :-)

**Comment by whit537** [comment]
Alright, perms configured. Gonna rebuild at AppVeyor ...

**Comment by pjz** [comment]
...and there's the status button.

**Comment by whit537** [comment]
Yesssss.

**Comment by pjz** [comment]
Do you need to do the same dance over on `gratipay/aspen-python` ?

**Comment by whit537** [comment]
@pjz I added `aspen-python` to the "Continuous Integration" GitHub team when I created it.

**Comment by whit537** [comment]
(So we should be good to go there.)

**Comment by whit537** [comment]
> Sorry, I'm not sure I understand -- can you clarify what exactly you mean by "limit the entire account"? Sharing as many details as possible is always helpful.

----

> By "limit the entire account" I mean "not have to grant full push access to the account." Here's the PR which prompted this request:
>
https://github.com/gratipay/filesystem_tree.py/pull/11
>
Basically, the `repo:status` OAuth scope is of limited utility since the account must have full push access to the repo in order to take advantage of `repo:status`. I want to be able to grant `repo:status` without having to grant full push access. Make sense? :-)

----

>Thanks for clarifying, makes sense now. That's not possible currently, but adding more options for configuring those permissions is already on the API team's radar. I can't promise an ETA, but just wanted to let you know it's something the team is thinking about as well. I'll pass your feedback along to the team.
>
If there's anything else you'd like to see improved -- let me know.

**Pull request merged**
