### PR TITLE
Make doctests failable

### PR DESCRIPTION
**Pull request by pjz**
Make runtests.sh fail if doctests fail

### CODE REVIEW

**Comment by pjz** [comment]
This should be merged even if it fails, as the whole point is that it *allow* the doctests to cause a failure, which wasn't possible before.

**Comment by whit537** [comment]
But then we've got a failing master, and who knows when we'll be able to fix it? I think we should fix the doctests as part of this PR—it looks like they're simply portability issues anyway.

**Comment by pjz** [comment]
we've *had* a failing master, we just didn't know about it.

**Comment by pjz** [comment]
and, you know, if it's so easy to fix, PRs accepted!

**Comment by whit537** [comment]
http://python3porting.com/problems.html#running-doctests

**Comment by pjz** [comment]
Right, so the fix was nontrivial, so I pulled this out separately so we can at least know when/if it gets fixed.

**Comment by whit537** [comment]
Closing in favor of #13.

**Pull request closed without merging**
