### PR TITLE
Add build status badge to README

### PR DESCRIPTION
**Pull request by pjz**

### CODE REVIEW

**Comment by whit537** [comment]
Since the README is simply a pointer to [Read the Docs](http://filesystem-tree-py.readthedocs.org/en/1.0.1/), I think we should add the badge to the documentation, right after "We test against Python 2.6, 2.7, 3.2, and 3.3."

**Comment by pjz** [comment]
I was just thinking it would be nice to have status on the front github page.

**Comment by whit537** [comment]
Why would we duplicate the build status badge on the front page of GitHub and not any of the other info from http://filesystem-tree-py.readthedocs.org/en/1.0.1/? How do we decide what info to duplicate?

Whatever we decide, we should make the GitHub front pages consistent across [all of our Python libraries](https://github.com/gratipay/?utf8=%E2%9C%93&query=.py).

**Comment by pjz** [comment]
..so that I don't have to leave the repo to see the build status - separating those two things seems odd.

**Comment by whit537** [comment]
Why would we not duplicate any of the other info from http://filesystem-tree-py.readthedocs.org/en/1.0.1/? How do we decide what info to duplicate?

**Comment by pjz** [comment]
A brief overview - project name, purpose, etc, - is likely appropriate.  It ends up being a kind of overview/title page on Github.

**Comment by whit537** [comment]
#15 would solve this.

**Pull request closed without merging**
